"""with team and student names

Revision ID: 606d02805666
Revises: 727fa1abf952
Create Date: 2020-06-12 12:00:13.670739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606d02805666'
down_revision = '727fa1abf952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.Text(), nullable=True))
        batch_op.drop_column('firstname')
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('firstname', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
