"""first
Revision ID: 727fa1abf952
Revises: 84ccbd5a48bb
Create Date: 2020-06-08 21:58:20.474408
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727fa1abf952'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('firstname', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    op.drop_column('team', 'name')
    # ### end Alembic commands ###